// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MijiaProductGallery.Infrastructure.Database;

#nullable disable

namespace MijiaProductGallery.Infrastructure.Migrations
{
    [DbContext(typeof(GalleryDbContext))]
    [Migration("20260928154311_AddProductRandomKey")]
    partial class AddProductRandomKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MijiaProductGallery.Core.Models.AppSettingEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("MijiaProductGallery.Core.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedUnix")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedUnix")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Collections", (string)null);
                });

            modelBuilder.Entity("MijiaProductGallery.Core.Models.CollectionItem", b =>
                {
                    b.Property<int>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AddedUnix")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("CollectionId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CollectionItems", (string)null);
                });

            modelBuilder.Entity("MijiaProductGallery.Core.Models.FavoriteItem", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedUnix")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.HasIndex("CreatedUnix");

                    b.ToTable("Favorites", (string)null);
                });

            modelBuilder.Entity("MijiaProductGallery.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreateTimeUnix")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FirstSeenUnix")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageFormat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageHeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageWidth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenUnix")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RandomKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubCategory")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdateTimeUnix")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Brand");

                    b.HasIndex("Category");

                    b.HasIndex("IsAvailable");

                    b.HasIndex("Model")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("RandomKey");

                    b.HasIndex("Sha256");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("MijiaProductGallery.Core.Models.ProductUsage", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CopyCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DragCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastUsedUnix")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalUseCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.HasIndex("LastUsedUnix");

                    b.HasIndex("TotalUseCount");

                    b.ToTable("ProductUsages", (string)null);
                });

            modelBuilder.Entity("MijiaProductGallery.Core.Models.SearchHistoryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedUnix")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUnix");

                    b.HasIndex("Query")
                        .IsUnique();

                    b.ToTable("SearchHistories", (string)null);
                });

            modelBuilder.Entity("MijiaProductGallery.Core.Models.SyncChange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Change")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DetailJson");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SyncRunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Model");

                    b.HasIndex("SyncRunId");

                    b.HasIndex("Type");

                    b.ToTable("SyncChanges", (string)null);
                });

            modelBuilder.Entity("MijiaProductGallery.Core.Models.SyncRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Counts")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EndedUnix")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stage")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedUnix")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Trigger")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartedUnix");

                    b.ToTable("SyncRuns", (string)null);
                });

            modelBuilder.Entity("MijiaProductGallery.Core.Models.SyncState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastSuccessfulSyncUnix")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSyncUnix")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnapshotDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncState", (string)null);
                });

            modelBuilder.Entity("MijiaProductGallery.Core.Models.UsageEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UsedUnix")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsedUnix");

                    b.HasIndex("ProductId", "UsedUnix");

                    b.ToTable("UsageEvents", (string)null);
                });

            modelBuilder.Entity("MijiaProductGallery.Core.Models.CollectionItem", b =>
                {
                    b.HasOne("MijiaProductGallery.Core.Models.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MijiaProductGallery.Core.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MijiaProductGallery.Core.Models.FavoriteItem", b =>
                {
                    b.HasOne("MijiaProductGallery.Core.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MijiaProductGallery.Core.Models.ProductUsage", b =>
                {
                    b.HasOne("MijiaProductGallery.Core.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MijiaProductGallery.Core.Models.SyncChange", b =>
                {
                    b.HasOne("MijiaProductGallery.Core.Models.SyncRun", null)
                        .WithMany()
                        .HasForeignKey("SyncRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MijiaProductGallery.Core.Models.UsageEvent", b =>
                {
                    b.HasOne("MijiaProductGallery.Core.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
